version: "3.8"
services:
  app:
    image: paprikar/default-discord-bot:latest
    restart: always
    env_file:
      - .env
    depends_on:
      - database
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
