name: Build

on:
  push:
    branches: [ master ]
    paths:
      - src/**
      - pom.xml
  pull_request:
    branches: [ master ]
    paths:
      - src/**
      - pom.xml

jobs:
  build_and_verify:
    name: Build and Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Verify
        run: mvn -B -U verify
